services:
    ChainCommandBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Tests}'

    ChainCommandBundle\EventSubscriber\ChainCommandSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    ChainCommandBundle\Service\CommandChainRegistry: ~
